version: "3"

services:
  rfactor2:
    build: .
    restart: always
    stop_signal: SIGINT
    ports:
      # server manager web interface port
      - 6080:80
      - 54297:54297
      - 54297:54297/udp
      - 64297:64297
      - 64298:64298/udp
      - 64299:64299/udp
    volumes:
      - ./Packages:/home/usr/rf2/Packages
      - /dev/shm:/dev/shm
    environment:
      VNC_PASSWORD: changeme 
      RESOLUTION: 1440x720
